name: RealityCheck AI CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run Tests
      run: |
        pip install pytest
        pytest backend/tests

    - name: Run API Test
      run: |
        pip install uvicorn
        uvicorn backend.app:app --host 127.0.0.1 --port 8000 &
        sleep 5
        curl -X POST http://127.0.0.1:8000/analyze \
        -H "Content-Type: application/json" \
        -d '{"text":"test fake news"}'
